name: Go CI for task_manager_v2

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.22.5'

    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('task_manager_v2/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Install dependencies
      run: |
        cd clean_archtecture_tm
        go mod download

    - name: Print environment variables
      run: |
        echo "MONGODB_URI: $MONGODB_URI"

    - name: Run tests
      env:
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
      run: |
        cd clean_archtecture_tm
        go test -v ./...

    - name: Build
      run: |
        cd clean_archtecture_tm
        go build -v ./...
